### ISSUE TITLE
Arrays seem to use the indefinite array representation rather than the fixed width.

### ISSUE THREAD

**Issue by daidoji** [Ledest/ecbor#3]
When using https://hexdocs.pm/cbor/readme.html#encoding as in their example we have
```elixir
CBOR.encode([1, [2, 3]])
<<130, 1, 130, 2, 3>>
```

When using python cbor2 we get
```python
>>> cbor2.dumps([1,2,3,4])
b'\x84\x01\x02\x03\x04'
```

However, when using ecbor we get
```erlang
ecbor:encode([1, 2, 3, 4]).
<<159,1,2,3,4,255>>
```

Probably fixed widths should use the fixed array representation to match other implementations.

**Comment by Ledest** [comment]
`[1, 2, 3, 4]` is a list, not an array.
"fixed array" (with index access) in Erlang is a tuple.

**Comment by daidoji** [comment]
So we should construct tuples when we want to be compatible with these other libraries?

**Comment by Ledest** [comment]
Maybe. If "other libraries" cannot understand CBOR's infinite "arrays" :)

**Comment by daidoji** [comment]
Roger, we'll do some testing and close this issue then if tuples will do.
